# Project
site_name: 'techblog@vegardhw.net
site_description: 'Technical ramblings'
site_author: 'Vegard Hoff Walmsness'
site_url: https://blog.vegardhw.net

# Repository
repo_name: vegardhw/blog
repo_url: https://github.com/vegardhw/blog

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
  - macros
  - mkdocs-video

markdown_extensions:
  - pymdownx.snippets
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - lightgallery
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

extra:
  social:
    - icon:  fontawesome/brands/github
      link:  https://github.com/vegardhw
    - icon:  fontawesome/brands/slack
      link:  https://someone.slack.com
#    - icon:  fontawesome/solid/envelope
#      link:  mailto:someone@mail.com

nav:
  - Home: index.md
  - About: about.md
#  - Applications: apps.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
#    - navigation.tracking
#    - navigation.tabs.sticky
#    - navigation.expand
#   - toc.integrate
  logo: https://asite.com/alogo.svg
  favicon: https://asite.com/alogo.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        # icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      # primary: purple
      # accent: amber
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        # icon: material/toggle-switch
        name: Switch to light mode
      # primary: purple
      # accent: amber
extra_css:
  - stylesheets/mkdocs.css
